const fs = require('node:fs');
const report = JSON.parse(fs.readFileSync('build/google-play/report/validation.json', 'utf8'));
const text = `## Google Play candidate - NOT published

Package: ${report.packageName}
Version: ${report.versionName} (${report.versionCode})
Commit: ${report.commit}
AAB SHA-256: ${report.aabSha256}
Upload certificate SHA-256: ${report.uploadCertificateSha256}
Current direct APK versionCode: ${report.directApkVersionCode}
Operator-declared highest prior Play versionCode: ${report.operatorDeclaredPreviousPlayVersionCode}

The artifact contains the signed AAB, final merged manifest, exhaustive permission
inventory, signature verification, and ELF LOAD alignment for every native library.
It does not include a keystore, passwords or an automatic store submission.

Before uploading, the authorized Console owner must confirm the highest Play code,
organization/developer verification, app access instructions, Data safety,
VpnService and foreground specialUse declarations, content rating, target audience,
privacy/disclosure and consent review. No account or contract acceptance is implied.
Play App Signing must use the EXISTING direct APK app-signing key to preserve
updates for com.sxbvpn.mobile. The AAB upload certificate alone is NOT proof of the
certificate Play will use to sign delivered APKs. Confirm the Console app-signing
SHA-256 equals the current direct certificate before any rollout.

The direct APK and Play builds share the same UTC version allocator and lock.
Do not upload an older candidate after a newer build; re-run with the highest
previous Play code. Artifacts expire after 30 days. No Expo project is required
for this workflow; EAS requires a real project UUID (EAS_PROJECT_ID) and its own
authorized setup before use, and is not the validated native build route here.

Real-device evidence (not generated by this build):
1. Use a physical Android device or a separately provisioned Android emulator,
   including an Android 15/16 16 KiB image; adb shell getconf PAGE_SIZE must show 16384.
2. Install APKs derived from this exact AAB with pinned bundletool and the persistent
   signing key on an authorized machine. Never use a debug/temporary key for updates.
3. Capture actual onboarding, disclosure, acceptance/decline, activation and the
   Android VPN permission dialog. Use an authorized test account for a real VPN
   connection; do not fabricate a successful tunnel or use production credentials.
4. Capture at least two real phone screenshots using adb exec-out screencap -p.
   Record the VPN declaration demonstration with adb shell screenrecord
   --time-limit 90 /sdcard/sxb-vpn-declaration.mp4, then adb pull the file and
   remove it from the device. Keep the final demonstration at most 90 seconds.
   Screen recording contains user data: use a dedicated clean test profile.
5. Confirm cold-start/restart behavior, notifications and telemetry before/after
   consent, all native transports including DNSTT, and APK-to-Play update continuity.
No emulator, screenshots, recording, account access or runtime tunnel success is
claimed by the bundle validation report.
`;
fs.writeFileSync('build/google-play/report/RELEASE-HANDOFF.txt', text);
process.stdout.write(text);
