export const en = {
  app_name: 'SXB VPN',
  tagline: 'Browse securely',

  onboarding_title_1: 'Welcome to SXB VPN',
  onboarding_desc_1: 'Stay secure and private online with a fast, protected connection, wherever you are.',
  onboarding_title_2: 'Simple connection',
  onboarding_desc_2: 'Activate your account with a simple SXB Token. No configuration required.',
  onboarding_title_3: 'Easy top-up',
  onboarding_desc_3: 'Add a data plan instantly with your SXB Data Token.',
  onboarding_title_4: 'Ready to start',
  onboarding_desc_4: 'Your online security starts now. Activate your account and browse freely.',
  start: 'Get Started',
  next: 'Next',
  skip: 'Skip',

  activate_account_title: 'Account Activation',
  activate_account_desc: 'Enter your SXB Token to activate your account and access VPN protection.',
  token_user_placeholder: 'SXB-USER-XXXX-XXXX-XXXX',
  paste: 'Paste',
  scan_qr: 'Scan QR',
  activate: 'Activate',
  activate_btn: 'Activate my account',
  activating: 'Activating...',
  activation_success: 'Account activated successfully!',
  qr_soon_title: 'QR Code',
  qr_soon_body: 'QR code scanning will be available in a future release.\n\nEnter your token manually above.',
  ok: 'OK',
  token_not_found: 'Token not found. Please check the code.',
  token_used: 'Token already used.',
  token_expired_short: 'Token expired.',
  network_error: 'Network error. Please try again.',

  activate_account: 'Activate my account',
  activate_plan: 'Activate a plan',
  connect: 'Connect',
  connecting: 'Connecting...',
  disconnect: 'Disconnect',
  disconnecting: 'Disconnecting...',
  renew_plan: 'Renew my plan',
  contact_support: 'Contact support',
  loading: 'Loading...',
  user_default: 'User',

  greeting_morning: 'Good morning',
  greeting_afternoon: 'Good afternoon',
  greeting_evening: 'Good evening',
  greeting_default: 'Hello 👋',
  account_active: 'Account active',
  account_suspended: 'Account suspended',
  protection_active: 'Protection active',
  protection_inactive: 'Protection inactive',
  connecting_status: 'Connecting...',
  tap_to_connect: 'Tap to connect',
  tap_to_disconnect: 'Tap to disconnect',
  view_connection_logs: 'View connection logs',
  logs_in_progress: 'In progress…',
  logs_engine_title: 'VPN engine logs',
  logs_copy_all: 'Copy',
  logs_copy_a11y: 'Copy all logs',
  logs_copy_hint: 'One tap "Copy" = full history (share or clipboard), ready to paste.',
  logs_waiting: 'Waiting for connection...',
  card_quota_plan: 'PLAN QUOTA',
  card_traffic_realtime: 'REAL-TIME TRAFFIC',
  card_traffic_per_app: 'PER-APP TRAFFIC',
  card_connection_info: 'CONNECTION INFO',
  no_app_data: 'No per-app data available',
  revocation_msg_revoked: 'This configuration has been revoked by the administrator.',
  revocation_msg_suspended: 'Your account is suspended. Contact support.',
  revocation_msg_expired: 'Your subscription has expired. Renew it.',
  revocation_msg_disabled: 'This configuration is disabled.',

  current_plan: 'Your plan',
  expires_on: 'Expires on',
  no_active_plan: 'No active plan',
  add_plan: 'Add a plan',
  days_left: 'days left',
  day_left: 'day left',
  expired_plan: 'Plan expired',
  of: 'of',
  gb: 'GB',
  mb: 'MB',
  kb: 'KB',

  activate_plan_title: 'Activate a plan',
  activate_plan_desc: 'Enter your SXB Data Token to add a plan to your account.',
  token_data_placeholder: 'SXB-DATA-XXXX-XXXX-XXXX',
  plan_activating: 'Activating...',
  plan_success: 'Plan activated successfully!',
  quota_added: 'Quota added',

  home: 'Home',
  history: 'History',
  profile: 'Profile',
  notifications: 'Notifications',
  alerts_tab: 'Alerts',

  no_history: 'No activity recorded',
  account_activated_event: 'Account activated',
  plan_activated_event: 'Plan activated',
  vpn_connected_event: 'VPN connected',
  vpn_disconnected_event: 'VPN disconnected',
  plan_expired_event: 'Plan expired',
  plan_renewed_event: 'Plan renewed',
  filter_all: 'All',
  filter_connections: 'Connections',
  filter_activations: 'Activations',

  mark_all_read: 'Mark all as read',
  no_notifications: 'No notifications',
  no_notifications_desc: 'You have no notifications yet.',
  notif_plan_expired: 'Your SXB VPN plan has expired.',
  notif_low_quota_100mb: 'You have 100 MB of data remaining.',
  notif_expires_tomorrow: 'Your plan expires tomorrow.',
  notif_new_config: 'New VPN configuration available.',
  notif_sync_done: 'Synchronization complete.',
  notifications_read_all: 'Mark all read',
  notifications_empty_hint: 'You will be alerted about important events.',
  time_minutes_short: ' min',
  time_hours_short: ' h',
  time_days_short: ' d',

  client_id: 'Client ID',
  plan_label: 'Plan',
  expiration: 'Expiration',
  devices_authorized: 'Authorized devices',
  app_version: 'App version',
  logout: 'Log out',
  logout_confirm_title: 'Log out',
  logout_confirm_message: 'Are you sure you want to log out?',
  logout_confirm_local: 'Your local session will be cleared. Your account remains active.',
  logout_confirm_local_short: 'Your local session will be cleared.',
  cancel: 'Cancel',
  confirm: 'Confirm',
  no_expiry: 'Unlimited',
  device: 'device',
  devices: 'devices',
  section_personal_info: 'Personal information',
  section_authorized_devices: 'Authorized devices',
  section_security_conn: 'Security & Connection',
  status_no_package: 'No plan',
  status_unknown: 'Unknown',

  settings: 'Settings',
  language_section: 'Language',
  french: 'Français',
  english: 'English',
  theme_section: 'Appearance',
  theme_dark: 'Dark',
  theme_light: 'Light',
  theme_system: 'System',
  notifications_section: 'Notifications',
  notifications_enable: 'Enable notifications',
  security_section: 'Security',
  biometrics: 'Biometric unlock',
  about_section: 'About',
  version: 'Version',
  terms: 'Terms of service',
  privacy_policy: 'Privacy policy',
  cgu_button: 'Terms / Privacy',
  cgu_modal_title: 'Terms & Privacy Policy',
  close: 'Close',
  build_label: 'Build',
  diagnostic_section: 'DIAGNOSTIC',
  diagnostic_subtitle: 'VPN tunnel debug tools (dev only)',
  diagnostic_row: 'VPN Diagnostic',
  dev_badge: 'DEV',
  appearance_lang_section: 'APPEARANCE & LANGUAGE',
  theme_dark_row: 'Dark theme',
  language_row: 'Language',
  push_notifications: 'Push notifications',
  plan_expiration_alerts: 'Plan expiration alerts',
  local_data_section: 'LOCAL DATA',
  stored_data: 'Stored data',
  clear_local_data_btn: 'Clear local data',
  clear_local_data_title: 'Clear local data',
  clear_local_data_msg: 'This action removes the VPN configuration, logs and local preferences. Your account will not be deleted.',
  clear: 'Clear',
  data_cleared: 'Data cleared',
  data_cleared_msg: 'Local data has been removed.',
  kill_switch_enabled_title: 'Kill Switch enabled',
  kill_switch_enabled_msg: 'All internet traffic will be blocked if the VPN disconnects.',
  config_synced_title: 'VPN configuration synced from the server.',
  config_sync_error_msg: 'Unable to sync the configuration. Check your connection.',
  device_id_row: 'Device ID',
  pin_lock_row: 'PIN code lock',
  biometrics_row: 'Biometric authentication',
  biometrics_soon_title: 'Coming soon',
  biometrics_soon_msg: 'Biometrics will be enabled in a future release.',
  package_section: 'PLAN',
  quota_used_row: 'Quota used',
  vpn_row_section: 'VPN',
  active_protocol_row: 'Active protocol',
  auto_value: 'AUTO',
  auto_reconnect_row: 'Auto-reconnect',
  kill_switch_row: 'Kill Switch',
  on_value: 'ON',
  off_value: 'OFF',
  view_vpn_logs_row: 'View VPN logs',
  security_section_uc: 'SECURITY',
  about_section_uc: 'ABOUT',
  notifications_section_uc: 'NOTIFICATIONS',

  account_section: 'Account',
  device_id: 'Device ID',
  subscription_status: 'Subscription status',
  subscription_active: 'Active',
  subscription_expired: 'Expired',
  subscription_none: 'No plan',

  vpn_section: 'VPN',
  refresh_config: 'Refresh configuration',
  refreshing_config: 'Syncing...',
  refresh_config_success: 'Configuration updated!',
  refresh_config_error: 'Unable to sync configuration',
  kill_switch: 'Kill Switch',
  kill_switch_desc: 'Block all traffic if VPN disconnects',
  vpn_logs: 'VPN logs',
  clear_logs: 'Clear logs',

  data_section: 'Local data',
  clear_cache: 'Clear local cache',
  clear_cache_confirm: 'Clear all local data?',
  clear_cache_success: 'Cache cleared successfully',

  support: 'Support',
  faq: 'FAQ',
  faq_q1: 'How do I activate my account?',
  faq_a1: 'Enter your SXB-USER Token on the activation screen. The token was provided when you registered.',
  faq_q2: 'How do I add a plan?',
  faq_a2: 'Tap "Activate a plan" and enter your SXB-DATA Data Token.',
  faq_q3: 'What should I do if my connection doesn\'t work?',
  faq_a3: 'Check your internet connection, then disconnect and reconnect the VPN. If the issue persists, contact support.',
  faq_q4: 'My plan has expired, what should I do?',
  faq_a4: 'Contact your reseller to get a new Data Token and activate it in the app.',
  faq_q5: 'Does the VPN stay active when I close the app?',
  faq_a5: 'Yes. A foreground service ensures the VPN tunnel stays active in the background and when the screen is locked.',
  faq_activate_q: 'How do I activate my account?',
  faq_vpn_ko_q: 'My VPN won\'t connect',
  faq_vpn_ko_a: 'Check your internet connection, then make sure your plan is active and not expired.',
  faq_renew_q: 'How do I renew my plan?',
  faq_devices_q: 'How many devices can I use?',
  faq_devices_a: 'The number of authorized devices depends on your plan. Check your profile for the limit.',
  contact_whatsapp: 'WhatsApp',
  contact_email: 'Email',
  contact_discord: 'Discord',
  ticket_subject_placeholder: 'Subject',
  ticket_message_placeholder: 'Describe your issue...',
  send: 'Send',
  sent: 'Sent!',
  create_ticket: 'Create a ticket',
  my_tickets: 'My tickets',
  contact_us: 'Contact us',
  contact_via_whatsapp: 'WhatsApp',
  contact_via_email: 'Email',
  ticket_submit: 'Send',
  ticket_submitting: 'Sending...',
  ticket_success: 'Your message has been sent successfully.',
  ticket_load_failed: 'Unable to load your tickets. Check your connection.',
  ticket_send_failed: 'Your ticket was not sent. Check your connection and try again.',
  ticket_empty: 'You do not have any tickets yet.',
  ticket_open: 'Open',
  ticket_in_progress: 'In progress',
  ticket_resolved: 'Resolved',
  ticket_closed: 'Closed',
  ticket_updated_at: 'Updated',
  hero_sub: 'Our team is here to help you.',

  error_invalid_token: 'Invalid token. Please check and try again.',
  error_expired_token: 'This token has expired.',
  error_suspended: 'Your account is suspended. Contact support.',
  error_no_network: 'Connection failed. Check your network.',
  error_server: 'Server error. Please try again later.',
  error_generic: 'An error occurred. Please try again.',
  error_quota_empty: 'Insufficient quota.',
  error_vpn_permission: 'VPN permission required. Grant access in Android settings.',
  retry: 'Retry',
  back: 'Back',
  oops: 'Oops!',

  just_now: 'Just now',
  minutes_ago: 'min',
  hours_ago: 'h',
  today: 'Today',
  yesterday: 'Yesterday',

  active: 'Active',
  inactive: 'Inactive',
  expired: 'Expired',
  suspended_status: 'Suspended',
  no_package_status: 'No plan',

  onboarding_security_title: 'Total security',
  onboarding_security_desc: 'Your connection encrypted, your identity protected. Anywhere. Always.',
  onboarding_oneclick_title: 'One tap is enough',

  // VPN — Traffic
  traffic_realtime: 'REAL-TIME TRAFFIC',
  traffic_sent: 'Sent',
  traffic_received: 'Received',
  traffic_speed: 'Speed',
  traffic_upload: 'Upload',
  traffic_download: 'Download',
  traffic_session: 'Session',

  // StepLogs — technical labels (kept for compat)
  step_preparing: 'Preparing…',
  step_checking_security: 'Checking security…',
  step_security_ok: 'Secure environment',
  step_loading_config: 'Loading configuration…',
  step_config_loaded: 'Configuration loaded',
  step_provisioning: 'Secure provisioning…',
  step_provisioned: 'Configuration provisioned',
  step_syncing: 'Syncing…',
  step_synced: 'Data synced',
  step_connecting: 'Connecting to server…',
  step_handshake: 'Secure handshake…',
  step_establishing_tunnel: 'Establishing tunnel…',
  step_tunnel_ready: 'Secure tunnel ready',
  step_vpn_active: 'VPN connected',
  step_error: 'Connection error',
  step_disconnecting: 'Disconnecting…',
  step_disconnected: 'VPN disconnected',
  step_reconnecting: 'Auto-reconnecting…',
  step_quota_check: 'Checking quota…',
  step_quota_ok: 'Sufficient quota',
  step_quota_exhausted: 'Quota exhausted',
  step_expired: 'Subscription expired',
  step_revoked: 'Configuration revoked',
  step_suspended: 'Account suspended',
  step_permission_check: 'Checking permissions…',
  step_permission_granted: 'Permission granted',
  step_permission_denied: 'Permission denied',

  // StepLogs — user-friendly wording
  friendly_header: 'Connecting',
  friendly_a11y_progress: 'VPN connection progress',
  friendly_preparing: 'Preparing connection…',
  friendly_security: 'Checking your device security…',
  friendly_security_ok: 'Device is secure',
  friendly_permission: 'Android VPN authorization…',
  friendly_permission_ok: 'Authorization granted',
  friendly_permission_denied: 'Authorization denied by Android',
  friendly_config: 'Loading your configuration…',
  friendly_config_ok: 'Configuration ready',
  friendly_provisioning: 'Preparing secure profile…',
  friendly_provisioning_ok: 'Secure profile ready',
  friendly_syncing: 'Syncing with the service…',
  friendly_synced: 'Data up to date',
  friendly_quota: 'Checking your plan…',
  friendly_quota_ok: 'Plan valid',
  friendly_quota_exhausted: 'Quota exhausted — recharge your plan',
  friendly_expired: 'Subscription expired',
  friendly_connecting: 'Connecting to SXB server…',
  friendly_handshake: 'Encrypted security exchange…',
  friendly_tunnel: 'Creating the secure tunnel…',
  friendly_tunnel_ok: 'Secure tunnel ready',
  friendly_connected: 'Connection established — you\'re protected',
  friendly_connected_final: '✅ Connected — you\'re browsing securely',
  friendly_disconnecting: 'Closing the tunnel…',
  friendly_disconnected: 'Disconnected',
  friendly_reconnecting: 'Auto-reconnecting…',
  friendly_revoked: 'Configuration revoked by the administrator',
  friendly_suspended: 'Account suspended — contact support',
  friendly_error: 'An error occurred during connection',

  // Multi-config
  config_select: 'Select',
  config_active: 'Active',
  config_inactive: 'Inactive',
  config_max_reached: 'Maximum 2 configurations reached',
  config_switch: 'Switch configuration',
  config_saved: 'Configuration saved',
  config_removed: 'Configuration removed',

  // VPN Connections
  vpn_connections: 'VPN CONNECTIONS',
  no_vpn_connections: 'No VPN connections configured',
  ask_admin_for_plan: 'Ask your administrator to create a plan',
  connection_expired: 'Expired',
  connection_revoked: 'Revoked',
  connection_suspended: 'Suspended',
  connection_active: 'Active',
  connection_disabled: 'Disabled',

  // VPN — Auto-reconnect
  auto_reconnect: 'Auto-reconnect',
  auto_reconnect_desc: 'Automatically reconnect if the connection is lost',

  // Quota (deduplicated)
  quota_total: 'Total',
  quota_used: 'Used',
  quota_remaining: 'Remaining',
  quota_remaining_full: 'Remaining quota',
  quota_exhausted: 'Quota exhausted',
  quota_reload: 'Reload your plan',

  // Expiration
  config_expired: 'Configuration expired',
  config_expires_at: 'Expires on',

  // Connection Info
  info_protocol: 'Protocol',
  info_last_conn: 'Last conn.',
  info_ip_address: 'IP Address',
  info_ping: 'Ping',

  // VPN Notifications
  notif_connected: 'VPN connected',
  notif_disconnected: 'VPN disconnected',
  notif_reconnecting: 'Reconnecting...',
  notif_error: 'VPN connection error',
  notif_kill_switch: 'Kill Switch active — connection blocked',

  // In-app update
  update_available_title: 'New version available',
  update_available_body: 'A new version of SXB VPN is ready. Your data will be preserved.',
  update_current_label: 'Current version',
  update_new_label: 'New version',
  update_download: 'Download',
  update_later: 'Later',
  update_downloading: 'Downloading…',
  update_downloading_pct: 'Downloading… ({pct}%)',
  update_install_prompt: 'Opening installer…',
  update_install_error: 'Cannot open installer. Please retry.',
  update_download_error: 'Download failed. Check your connection.',
  update_up_to_date: 'App is up to date',
  update_check_failed: 'Unable to check for updates',
} as const;
