export const en = {
  app_name: 'SXB VPN',
  tagline: 'Browse securely',

  onboarding_title_1: 'Welcome to SXB VPN',
  onboarding_desc_1: 'Stay secure and private online with a fast, protected connection, wherever you are.',
  onboarding_title_2: 'Simple connection',
  onboarding_desc_2: 'Activate your account with a simple SXB Token. No configuration required.',
  onboarding_title_3: 'Easy top-up',
  onboarding_desc_3: 'Add a data plan instantly with your SXB Data Token.',
  onboarding_title_4: 'Ready to start',
  onboarding_desc_4: 'Your online security starts now. Activate your account and browse freely.',
  start: 'Get Started',
  next: 'Next',
  skip: 'Skip',

  activate_account_title: 'Account Activation',
  activate_account_desc: 'Enter your SXB Token to activate your account and access VPN protection.',
  token_user_placeholder: 'SXB-USER-XXXX-XXXX-XXXX',
  paste: 'Paste',
  scan_qr: 'Scan QR',
  activate: 'Activate',
  activating: 'Activating...',
  activation_success: 'Account activated successfully!',

  activate_account: 'Activate my account',
  activate_plan: 'Activate a plan',
  connect: 'Connect',
  connecting: 'Connecting...',
  disconnect: 'Disconnect',
  disconnecting: 'Disconnecting...',
  renew_plan: 'Renew my plan',
  contact_support: 'Contact support',

  greeting_morning: 'Good morning',
  greeting_afternoon: 'Good afternoon',
  greeting_evening: 'Good evening',
  account_active: 'Account active',
  account_suspended: 'Account suspended',
  protection_active: 'Protection active',
  protection_inactive: 'Protection inactive',
  connecting_status: 'Connecting...',
  tap_to_connect: 'Tap to connect',
  tap_to_disconnect: 'Tap to disconnect',

  current_plan: 'Your plan',
  quota_remaining: 'Remaining quota',
  quota_used: 'Used quota',
  expires_on: 'Expires on',
  no_active_plan: 'No active plan',
  add_plan: 'Add a plan',
  days_left: 'days left',
  day_left: 'day left',
  expired_plan: 'Plan expired',
  of: 'of',
  gb: 'GB',
  mb: 'MB',
  kb: 'KB',

  activate_plan_title: 'Activate a plan',
  activate_plan_desc: 'Enter your SXB Data Token to add a plan to your account.',
  token_data_placeholder: 'SXB-DATA-XXXX-XXXX-XXXX',
  plan_activating: 'Activating...',
  plan_success: 'Plan activated successfully!',
  quota_added: 'Quota added',

  home: 'Home',
  history: 'History',
  profile: 'Profile',
  notifications: 'Notifications',

  no_history: 'No activity recorded',
  account_activated_event: 'Account activated',
  plan_activated_event: 'Plan activated',
  vpn_connected_event: 'VPN connected',
  vpn_disconnected_event: 'VPN disconnected',
  plan_expired_event: 'Plan expired',
  plan_renewed_event: 'Plan renewed',

  mark_all_read: 'Mark all as read',
  no_notifications: 'No notifications',
  no_notifications_desc: 'You have no notifications yet.',
  notif_plan_expired: 'Your SXB VPN plan has expired.',
  notif_low_quota_100mb: 'You have 100 MB of data remaining.',
  notif_expires_tomorrow: 'Your plan expires tomorrow.',
  notif_new_config: 'New VPN configuration available.',
  notif_sync_done: 'Synchronization complete.',

  client_id: 'Client ID',
  plan_label: 'Plan',
  expiration: 'Expiration',
  devices_authorized: 'Authorized devices',
  app_version: 'App version',
  logout: 'Log out',
  logout_confirm_title: 'Log out',
  logout_confirm_message: 'Are you sure you want to log out?',
  cancel: 'Cancel',
  confirm: 'Confirm',
  no_expiry: 'Unlimited',
  device: 'device',
  devices: 'devices',

  settings: 'Settings',
  language_section: 'Language',
  french: 'Français',
  english: 'English',
  theme_section: 'Appearance',
  theme_dark: 'Dark',
  theme_light: 'Light',
  theme_system: 'System',
  notifications_section: 'Notifications',
  notifications_enable: 'Enable notifications',
  security_section: 'Security',
  biometrics: 'Biometric unlock',
  about_section: 'About',
  version: 'Version',
  terms: 'Terms of service',
  privacy_policy: 'Privacy policy',

  account_section: 'Account',
  device_id: 'Device ID',
  subscription_status: 'Subscription status',
  subscription_active: 'Active',
  subscription_expired: 'Expired',
  subscription_none: 'No plan',

  vpn_section: 'VPN',
  refresh_config: 'Refresh configuration',
  refreshing_config: 'Syncing...',
  refresh_config_success: 'Configuration updated!',
  refresh_config_error: 'Unable to sync configuration',
  kill_switch: 'Kill Switch',
  kill_switch_desc: 'Block all traffic if VPN disconnects',
  vpn_logs: 'VPN logs',
  clear_logs: 'Clear logs',

  data_section: 'Local data',
  clear_cache: 'Clear local cache',
  clear_cache_confirm: 'Clear all local data?',
  clear_cache_success: 'Cache cleared successfully',

  support: 'Support',
  faq: 'FAQ',
  faq_q1: 'How do I activate my account?',
  faq_a1: 'Enter your SXB-USER Token on the activation screen. The token was provided when you registered.',
  faq_q2: 'How do I add a plan?',
  faq_a2: 'Tap "Activate a plan" and enter your SXB-DATA Data Token.',
  faq_q3: 'What should I do if my connection doesn\'t work?',
  faq_a3: 'Check your internet connection, then disconnect and reconnect the VPN. If the issue persists, contact support.',
  faq_q4: 'My plan has expired, what should I do?',
  faq_a4: 'Contact your reseller to get a new Data Token and activate it in the app.',
  faq_q5: 'Does the VPN stay active when I close the app?',
  faq_a5: 'Yes. A foreground service ensures the VPN tunnel stays active in the background and when the screen is locked.',
  create_ticket: 'Create a ticket',
  my_tickets: 'My tickets',
  contact_us: 'Contact us',
  contact_via_whatsapp: 'WhatsApp',
  contact_via_email: 'Email',
  ticket_subject: 'Subject',
  ticket_message: 'Message',
  ticket_submit: 'Send',
  ticket_submitting: 'Sending...',
  ticket_success: 'Your message has been sent successfully.',

  error_invalid_token: 'Invalid token. Please check and try again.',
  error_expired_token: 'This token has expired.',
  error_suspended: 'Your account is suspended. Contact support.',
  error_no_network: 'Connection failed. Check your network.',
  error_server: 'Server error. Please try again later.',
  error_generic: 'An error occurred. Please try again.',
  error_quota_empty: 'Insufficient quota.',
  error_vpn_permission: 'VPN permission required. Grant access in Android settings.',
  retry: 'Retry',
  back: 'Back',

  just_now: 'Just now',
  minutes_ago: 'min',
  hours_ago: 'h',
  today: 'Today',
  yesterday: 'Yesterday',

  active: 'Active',
  inactive: 'Inactive',
  expired: 'Expired',
  suspended_status: 'Suspended',
  no_package_status: 'No plan',
} as const;
