export const fr = {
  // App
  app_name: 'SXB VPN',
  tagline: 'Naviguez en sécurité',

  // Onboarding
  onboarding_title_1: 'Bienvenue sur SXB VPN',
  onboarding_desc_1: 'Naviguez en toute sécurité grâce à une connexion rapide et protégée, où que vous soyez.',
  onboarding_title_2: 'Connexion simplifiée',
  onboarding_desc_2: 'Activez votre compte avec un simple Token SXB. Pas de configuration, pas de prise de tête.',
  onboarding_title_3: 'Rechargez facilement',
  onboarding_desc_3: 'Ajoutez un forfait en un instant grâce à votre Token Data SXB.',
  onboarding_title_4: 'Prêt à commencer',
  onboarding_desc_4: 'Votre sécurité en ligne commence maintenant. Activez votre compte et naviguez librement.',
  start: 'Commencer',
  next: 'Suivant',
  skip: 'Passer',

  // Auth / Activation
  activate_account_title: 'Activation du compte',
  activate_account_desc: 'Entrez votre Token SXB pour activer votre compte et accéder à la protection VPN.',
  token_user_placeholder: 'SXB-USER-XXXX-XXXX-XXXX',
  paste: 'Coller',
  scan_qr: 'Scanner QR',
  activate: 'Activer',
  activate_btn: 'Activer mon compte',
  activating: 'Activation en cours...',
  activation_success: 'Compte activé avec succès !',
  qr_soon_title: 'QR Code',
  qr_soon_body: "Le scan de QR Code sera disponible dans la prochaine version.\n\nEntrez votre token manuellement ci-dessus.",
  ok: 'OK',
  token_not_found: 'Token introuvable. Vérifiez le code.',
  token_used: 'Token déjà utilisé.',
  token_expired_short: 'Token expiré.',
  network_error: 'Erreur réseau. Réessayez.',

  // Smart Button
  activate_account: 'Activer mon compte',
  activate_plan: 'Activer un forfait',
  connect: 'Se connecter',
  connecting: 'Connexion...',
  disconnect: 'Se déconnecter',
  disconnecting: 'Déconnexion...',
  renew_plan: 'Renouveler mon forfait',
  contact_support: 'Contacter le support',
  loading: 'Chargement...',
  user_default: 'Utilisateur',

  // Home
  greeting_morning: 'Bonjour',
  greeting_afternoon: 'Bonjour',
  greeting_evening: 'Bonsoir',
  greeting_default: 'Bonjour 👋',
  account_active: 'Compte actif',
  account_suspended: 'Compte suspendu',
  protection_active: 'Protection active',
  protection_inactive: 'Protection inactive',
  connecting_status: 'Connexion en cours...',
  tap_to_connect: 'Appuyez pour vous connecter',
  tap_to_disconnect: 'Appuyez pour vous déconnecter',
  view_connection_logs: 'Voir les logs de connexion',
  logs_in_progress: 'Progression…',
  logs_engine_title: 'Logs moteur VPN',
  logs_copy_all: 'Copier',
  logs_copy_a11y: 'Copier tous les logs',
  logs_copy_hint: 'Une touche « Copier » = tout l\'historique (partage ou presse-papiers), prêt à coller.',
  logs_waiting: 'En attente de connexion...',
  card_quota_plan: 'QUOTA DU FORFAIT',
  card_traffic_realtime: 'TRAFIC EN TEMPS RÉEL',
  card_traffic_per_app: 'CONSOMMATION PAR APPLICATION',
  card_connection_info: 'INFORMATIONS DE CONNEXION',
  no_app_data: 'Aucune donnée applicative disponible',
  revocation_msg_revoked: "Cette configuration a été révoquée par l'administrateur.",
  revocation_msg_suspended: 'Votre compte est suspendu. Contactez le support.',
  revocation_msg_expired: 'Votre abonnement a expiré. Renouvelez-le.',
  revocation_msg_disabled: 'Cette configuration est désactivée.',

  // Subscription Card
  current_plan: 'Votre forfait',
  expires_on: 'Expire le',
  no_active_plan: 'Aucun forfait actif',
  add_plan: 'Ajouter un forfait',
  days_left: 'jours restants',
  day_left: 'jour restant',
  expired_plan: 'Forfait expiré',
  of: 'sur',
  gb: 'Go',
  mb: 'Mo',
  kb: 'Ko',

  // Plan Activation
  activate_plan_title: 'Activer un forfait',
  activate_plan_desc: 'Entrez votre Token Data SXB pour ajouter un forfait à votre compte.',
  token_data_placeholder: 'SXB-DATA-XXXX-XXXX-XXXX',
  plan_activating: 'Activation en cours...',
  plan_success: 'Forfait activé avec succès !',
  quota_added: 'Quota ajouté',

  // Navigation
  home: 'Accueil',
  history: 'Historique',
  profile: 'Profil',
  notifications: 'Notifications',
  alerts_tab: 'Alertes',

  // History
  no_history: 'Aucune activité enregistrée',
  history_empty_hint: 'Les événements de votre compte apparaîtront ici.',
  activate_secure_badge: 'CONNEXION SÉCURISÉE',
  activate_token_title: 'Votre token SXB',
  activate_token_hint: 'Il active votre compte sur cet appareil.',
  activate_token_secure: 'Votre token est transmis de manière sécurisée',
  activate_footer: 'SXB VPN · Protection réseau fiable',
  copy: 'Copier',
  diagnostic_title: 'Diagnostic',
  diagnostic_live: 'Connexion en direct',
  diagnostic_steps: 'Étapes de connexion',
  logs_filter_errors: 'Erreurs',
  logs_filter_engine: 'Moteur',
  logs_ping_avg: 'Moyenne',
  logs_jitter: 'Gigue',
  logs_copy: 'Copier',
  logs_copied: 'Copié',
  logs_share: 'Partager',
  session_duration: 'Durée',
  engine_state: 'Moteur',
  delete: 'Supprimer',
  config_singular: 'profil',
  config_plural: 'profils',
  config_delete_title: 'Supprimer le profil',
  config_delete_confirm: 'Retirer « {name} » de cet appareil ? Le profil VPN sera supprimé localement.',
  config_manage: 'Gérer les profils',
  account_activated_event: 'Compte activé',
  plan_activated_event: 'Forfait activé',
  vpn_connected_event: 'VPN connecté',
  vpn_disconnected_event: 'VPN déconnecté',
  plan_expired_event: 'Forfait expiré',
  plan_renewed_event: 'Forfait renouvelé',
  filter_all: 'Tout',
  filter_connections: 'Connexions',
  filter_activations: 'Activations',

  // Notifications
  mark_all_read: 'Tout marquer comme lu',
  no_notifications: 'Aucune notification',
  no_notifications_desc: "Vous n'avez pas encore de notifications.",
  notif_plan_expired: 'Votre forfait SXB VPN a expiré.',
  notif_low_quota_100mb: 'Il vous reste 100 Mo de données.',
  notif_expires_tomorrow: 'Votre forfait expire demain.',
  notif_new_config: 'Nouvelle configuration VPN disponible.',
  notif_sync_done: 'Synchronisation terminée.',
  notifications_read_all: 'Tout lire',
  notifications_empty_hint: 'Vous serez averti des événements importants.',
  time_minutes_short: ' min',
  time_hours_short: ' h',
  time_days_short: ' j',

  // Profile
  client_id: 'Identifiant client',
  plan_label: 'Forfait',
  expiration: 'Expiration',
  devices_authorized: 'Appareils autorisés',
  app_version: "Version de l'application",
  logout: 'Déconnexion',
  logout_confirm_title: 'Déconnexion',
  logout_confirm_message: 'Êtes-vous sûr de vouloir vous déconnecter ?',
  logout_confirm_local: 'Votre session locale sera effacée. Votre compte reste actif.',
  logout_confirm_local_short: 'Votre session locale sera effacée.',
  cancel: 'Annuler',
  confirm: 'Confirmer',
  no_expiry: 'Illimité',
  device: 'appareil',
  devices: 'appareils',
  section_personal_info: 'Informations personnelles',
  section_authorized_devices: 'Appareils autorisés',
  section_security_conn: 'Sécurité & Connexion',
  status_no_package: 'Sans forfait',
  status_unknown: 'Inconnu',

  // Settings
  settings: 'Paramètres',
  language_section: 'Langue',
  french: 'Français',
  english: 'English',
  theme_section: 'Apparence',
  theme_dark: 'Sombre',
  theme_light: 'Clair',
  theme_system: 'Système',
  notifications_section: 'Notifications',
  notifications_enable: 'Activer les notifications',
  security_section: 'Sécurité',
  biometrics: 'Déverrouillage biométrique',
  about_section: 'À propos',
  version: 'Version',
  terms: "Conditions d'utilisation",
  privacy_policy: 'Politique de confidentialité',
  cgu_button: 'CGU / Politique de confidentialité',
  cgu_modal_title: 'CGU & Politique de confidentialité',
  close: 'Fermer',
  build_label: 'Build',
  diagnostic_section: 'DIAGNOSTIC',
  diagnostic_subtitle: 'Outils de débogage tunnel VPN (dev only)',
  diagnostic_row: 'Diagnostic VPN',
  dev_badge: 'DEV',
  diagnostic_warning: 'Mode temporaire : les hôtes, IP, SNI, réponses serveur et payloads sont visibles dans les logs. Les mots de passe et tokens restent masqués. Désactivez-le après le test.',
  appearance_lang_section: 'APPARENCE & LANGUE',
  theme_dark_row: 'Thème sombre',
  language_row: 'Langue',
  push_notifications: 'Notifications push',
  plan_expiration_alerts: 'Alertes expiration forfait',
  local_data_section: 'DONNÉES LOCALES',
  stored_data: 'Données stockées',
  clear_local_data_btn: 'Effacer les données locales',
  clear_local_data_title: 'Effacer les données locales',
  clear_local_data_msg: 'Cette action supprime la configuration VPN, les logs et les préférences locales. Votre compte ne sera pas supprimé.',
  clear: 'Effacer',
  data_cleared: 'Données effacées',
  data_cleared_msg: 'Les données locales ont été supprimées.',
  kill_switch_enabled_title: 'Kill Switch activé',
  kill_switch_enabled_msg: 'Toute connexion internet sera bloquée si le VPN se déconnecte.',
  config_synced_title: 'La configuration VPN a été synchronisée depuis le serveur.',
  config_sync_error_msg: 'Impossible de synchroniser la configuration. Vérifiez votre connexion.',
  device_id_row: 'ID Appareil',
  pin_lock_row: 'Verrouillage par code PIN',
  biometrics_row: 'Authentification biométrique',
  pin_setup_title: 'Créer un code PIN',
  pin_setup_hint: 'Choisissez 4 à 8 chiffres. Ce code sera votre secours si la biométrie échoue.',
  pin_verify_title: 'Confirmer votre code PIN',
  pin_verify_hint: 'Saisissez votre code actuel pour désactiver le verrouillage.',
  pin_confirm_label: 'Confirmer le code PIN',
  pin_format_error: 'Le code PIN doit contenir entre 4 et 8 chiffres.',
  pin_mismatch_error: 'Les deux codes PIN ne correspondent pas.',
  pin_enabled_message: 'Le verrouillage par code PIN est activé.',
  pin_disabled_message: 'Le verrouillage de l’application est désactivé.',
  biometric_enable_prompt: 'Confirmez votre identité pour activer la biométrie',
  biometric_enabled_message: 'Le déverrouillage biométrique est activé.',
  biometric_pin_required: 'Créez d’abord un code PIN de secours.',
  biometric_unavailable: 'Cet appareil ne dispose pas de biométrie compatible.',
  biometric_not_enrolled: 'Aucune donnée biométrique n’est enregistrée dans les réglages de l’appareil.',
  biometric_auth_failed: 'La biométrie n’a pas été confirmée. Elle reste désactivée.',
  unavailable_badge: 'INDISPONIBLE',
  app_lock_title: 'SXB VPN est verrouillé',
  app_lock_subtitle: 'Authentifiez-vous pour accéder à l’application.',
  app_lock_loading: 'Chargement du verrouillage sécurisé',
  app_lock_pin_label: 'Code PIN de secours',
  app_lock_unlock: 'Déverrouiller',
  app_lock_use_biometrics: 'Utiliser la biométrie',
  app_lock_biometric_prompt: 'Déverrouiller SXB VPN',
  app_lock_biometric_failed: 'Échec biométrique. Utilisez votre code PIN ou réessayez.',
  app_lock_pin_invalid: 'Code PIN incorrect.',
  app_lock_pin_throttled: 'Trop de tentatives. Réessayez dans 30 secondes.',
  app_lock_storage_error: 'Impossible de mettre à jour le verrouillage sécurisé.',
  app_lock_vpn_notice: 'Le tunnel VPN et sa notification restent actifs pendant le verrouillage.',
  package_section: 'FORFAIT',
  quota_used_row: 'Quota utilisé',
  vpn_row_section: 'VPN',
  active_protocol_row: 'Protocole actif',
  auto_value: 'AUTO',
  auto_reconnect_row: 'Reconnexion automatique',
  kill_switch_row: 'Kill Switch',
  on_value: 'ON',
  off_value: 'OFF',
  view_vpn_logs_row: 'Voir les logs VPN',
  security_section_uc: 'SÉCURITÉ',
  about_section_uc: 'À PROPOS',
  notifications_section_uc: 'NOTIFICATIONS',

  // Settings — Compte
  account_section: 'Compte',
  device_id: 'Identifiant appareil',
  subscription_status: 'Statut abonnement',
  subscription_active: 'Actif',
  subscription_expired: 'Expiré',
  subscription_none: 'Aucun forfait',

  // Settings — VPN
  vpn_section: 'VPN',
  refresh_config: 'Actualiser la configuration',
  refreshing_config: 'Synchronisation...',
  refresh_config_success: 'Configuration mise à jour !',
  refresh_config_error: 'Impossible de synchroniser la configuration',
  kill_switch: 'Kill Switch',
  kill_switch_desc: 'Bloquer tout le trafic si le VPN se déconnecte',
  vpn_logs: 'Journaux VPN',
  clear_logs: 'Effacer les journaux',

  // Settings — Données
  data_section: 'Données locales',
  clear_cache: 'Nettoyer le cache local',
  clear_cache_confirm: 'Effacer toutes les données locales ?',
  clear_cache_success: 'Cache effacé avec succès',

  // Support
  support: 'Support',
  faq: 'FAQ',
  faq_q1: 'Comment activer mon compte ?',
  faq_a1: "Entrez votre Token SXB-USER sur l'écran d'activation. Le token vous a été fourni lors de votre inscription.",
  faq_q2: 'Comment ajouter un forfait ?',
  faq_a2: "Appuyez sur « Activer un forfait » et entrez votre Token Data SXB-DATA.",
  faq_q3: 'Que faire si ma connexion ne fonctionne pas ?',
  faq_a3: "Vérifiez votre connexion internet, puis déconnectez et reconnectez le VPN. Si le problème persiste, contactez le support.",
  faq_q4: 'Mon forfait est expiré, que faire ?',
  faq_a4: 'Contactez votre revendeur pour obtenir un nouveau Token Data et activez-le dans l\'application.',
  faq_q5: 'Le VPN reste-t-il actif quand je ferme l\'application ?',
  faq_a5: 'Oui. Un service en premier plan garantit que le tunnel VPN reste actif en arrière-plan et lorsque l\'écran est verrouillé.',
  faq_activate_q: 'Comment activer mon compte ?',
  faq_vpn_ko_q: 'Mon VPN ne se connecte pas',
  faq_vpn_ko_a: 'Vérifiez votre connexion internet, puis assurez-vous que votre forfait est actif et non expiré.',
  faq_renew_q: 'Comment renouveler mon forfait ?',
  faq_devices_q: "Combien d'appareils puis-je utiliser ?",
  faq_devices_a: "Le nombre d'appareils autorisés dépend de votre forfait. Consultez votre profil pour voir la limite.",
  contact_whatsapp: 'WhatsApp',
  contact_email: 'Email',
  contact_discord: 'Discord',
  ticket_subject_placeholder: 'Sujet',
  ticket_message_placeholder: 'Décrivez votre problème...',
  send: 'Envoyer',
  sent: 'Envoyé !',
  create_ticket: 'Créer un ticket',
  my_tickets: 'Mes tickets',
  contact_us: 'Nous contacter',
  // duplicate removed
  ticket_submit: 'Envoyer',
  ticket_submitting: 'Envoi en cours...',
  ticket_success: 'Votre message a été envoyé avec succès.',
  ticket_load_failed: 'Impossible de charger vos tickets. Vérifiez votre connexion.',
  ticket_send_failed: 'Le ticket n’a pas été envoyé. Vérifiez votre connexion et réessayez.',
  ticket_empty: 'Vous n’avez encore aucun ticket.',
  ticket_open: 'Ouvert',
  ticket_in_progress: 'En cours',
  ticket_resolved: 'Résolu',
  ticket_closed: 'Clôturé',
  ticket_updated_at: 'Mis à jour',
  hero_sub: 'Notre équipe est disponible pour vous aider.',

  // Errors
  error_invalid_token: 'Token invalide. Vérifiez et réessayez.',
  error_expired_token: 'Ce token a expiré.',
  error_suspended: 'Votre compte est suspendu. Contactez le support.',
  activation_account_expired: 'L’accès du revendeur a expiré. Demandez son renouvellement.',
  activation_quota_reached: 'Le quota du revendeur est atteint. Aucune nouvelle activation n’est autorisée.',
  activation_forbidden: 'Activation refusée. Ce token n’est pas autorisé pour cet appareil ou ce client.',
  activation_rate_limited: 'Trop de tentatives. Patientez avant de réessayer.',
  error_no_network: 'Connexion impossible. Vérifiez votre réseau.',
  error_server: 'Erreur serveur. Veuillez réessayer plus tard.',
  error_generic: "Une erreur s'est produite. Veuillez réessayer.",
  error_quota_empty: 'Quota insuffisant.',
  error_vpn_permission: "Permission VPN requise. Accordez l'accès dans les paramètres Android.",
  retry: 'Réessayer',
  back: 'Retour',
  oops: 'Oups !',

  // Time
  just_now: "À l'instant",
  minutes_ago: 'min',
  hours_ago: 'h',
  today: "Aujourd'hui",
  yesterday: 'Hier',

  // Status
  active: 'Actif',
  inactive: 'Inactif',
  expired: 'Expiré',
  suspended_status: 'Suspendu',
  no_package_status: 'Aucun forfait',

  // Onboarding — Sécurité totale / One-click / etc.
  onboarding_security_title: 'Sécurité totale',
  onboarding_security_desc: 'Votre connexion chiffrée, votre identité protégée. Partout. Toujours.',
  onboarding_oneclick_title: 'Un clic suffit',

  // VPN — Paramètres
  auto_reconnect: 'Reconnexion automatique',
  auto_reconnect_desc: 'Se reconnecter automatiquement si la connexion est perdue',

  // VPN — Trafic
  traffic_realtime: 'TRAFIC EN TEMPS RÉEL',
  traffic_sent: 'Envoyé',
  traffic_received: 'Reçu',
  traffic_speed: 'Débit',
  traffic_upload: 'Upload',
  traffic_download: 'Download',
  traffic_session: 'Session',

  // StepLogs — Étapes techniques (labels bruts, gardés pour compat)
  step_preparing: 'Préparation…',
  step_checking_security: 'Vérification de sécurité…',
  step_security_ok: 'Environnement sécurisé',
  step_loading_config: 'Chargement de la configuration…',
  step_config_loaded: 'Configuration chargée',
  step_provisioning: 'Provisionnement sécurisé…',
  step_provisioned: 'Configuration provisionnée',
  step_syncing: 'Synchronisation…',
  step_synced: 'Données synchronisées',
  step_connecting: 'Connexion au serveur…',
  step_handshake: 'Négociation sécurisée…',
  step_establishing_tunnel: 'Établissement du tunnel…',
  step_tunnel_ready: 'Tunnel sécurisé prêt',
  step_vpn_active: 'VPN connecté',
  step_error: 'Erreur de connexion',
  step_disconnecting: 'Déconnexion…',
  step_disconnected: 'VPN déconnecté',
  step_reconnecting: 'Reconnexion automatique…',
  step_quota_check: 'Vérification du quota…',
  step_quota_ok: 'Quota suffisant',
  step_quota_exhausted: 'Quota épuisé',
  step_expired: 'Abonnement expiré',
  step_revoked: 'Configuration révoquée',
  step_suspended: 'Compte suspendu',
  step_permission_check: 'Vérification des permissions…',
  step_permission_granted: 'Permission accordée',
  step_permission_denied: 'Permission refusée',

  // StepLogs — Formulations grand public (affichées à l'utilisateur)
  friendly_header: 'Connexion en cours',
  friendly_a11y_progress: 'Progression de la connexion VPN',
  friendly_preparing: 'Préparation de la connexion…',
  walkthrough_welcome_title: 'Guide de démarrage',
  walkthrough_welcome_desc: 'Bienvenue ! Laissez-nous vous montrer comment utiliser votre nouvelle application SXB VPN.',
  walkthrough_vpn_btn_title: 'Bouton de Connexion',
  walkthrough_vpn_btn_desc: 'Appuyez ici pour activer ou désactiver instantanément votre protection VPN.',
  walkthrough_config_title: 'Vos Connexions',
  walkthrough_config_desc: 'Basculez facilement entre vos différentes configurations VPN ici.',
  walkthrough_quota_title: 'Suivi Data',
  walkthrough_quota_desc: 'Surveillez votre consommation en temps réel et votre quota restant.',
  walkthrough_actions_title: 'Actions Rapides',
  walkthrough_actions_desc: 'Accédez à votre historique, au support ou activez un nouveau forfait.',
  walkthrough_finish: "C'est parti !",
  tour_for: 'Guide pour',
  tour_getting_started: 'Premiers pas',
  tour_activation_eyebrow: 'ACTIVATION TERMINÉE',
  tour_activation_title: 'Votre espace sécurisé est prêt',
  tour_activation_desc: 'Votre compte est lié à cet appareil. Voici l’essentiel pour profiter de SXB VPN sans toucher aux réglages techniques.',
  tour_activation_bullet_1: 'Vos profils sensibles restent chiffrés sur cet appareil.',
  tour_activation_bullet_2: 'Un même forfait respecte la limite d’appareils définie par votre administrateur.',
  tour_home_eyebrow: 'ACCUEIL',
  tour_home_title: 'Une protection en un geste',
  tour_home_desc: 'Le grand bouton central démarre ou arrête le tunnel. Sa couleur et son texte indiquent toujours l’état réel de la connexion.',
  tour_home_bullet_1: 'Le chronomètre continue même lorsque l’application est en arrière-plan.',
  tour_home_bullet_2: 'Le ping et les débits confirment que les données circulent.',
  tour_profiles_eyebrow: 'CONFIGURATIONS',
  tour_profiles_title: 'Choisissez le service attribué',
  tour_profiles_desc: 'Si votre administrateur vous attribue plusieurs configurations, sélectionnez celle à utiliser depuis la carte en haut de l’accueil.',
  tour_profiles_bullet_1: 'Changer de profil coupe proprement l’ancien tunnel avant de lancer le nouveau.',
  tour_profiles_bullet_2: 'Les hôtes, mots de passe et paramètres techniques ne sont jamais affichés.',
  tour_quota_eyebrow: 'QUOTA & TRAFIC',
  tour_quota_title: 'Suivez vos données sans surprise',
  tour_quota_desc: 'Le total, le volume utilisé, le reste et l’expiration viennent du forfait attribué dans le dashboard.',
  tour_quota_bullet_1: 'La barre devient une alerte lorsque votre quota approche de sa limite.',
  tour_quota_bullet_2: 'Les débits montant et descendant sont mesurés pendant la connexion.',
  tour_sections_eyebrow: 'NAVIGATION',
  tour_sections_title: 'Chaque information à sa place',
  tour_sections_desc: 'Accueil pour le tunnel, Historique pour vos événements, Profil pour votre compte et Alertes pour les annonces importantes.',
  tour_sections_bullet_1: 'L’historique vous aide à comprendre vos dernières connexions.',
  tour_sections_bullet_2: 'Les alertes regroupent expiration, maintenance et mises à jour sécurisées.',
  tour_theme_eyebrow: 'APPARENCE',
  tour_theme_title: 'Clair, sombre ou automatique',
  tour_theme_desc: 'Choisissez le rendu qui vous convient dans Paramètres. Le mode système suit automatiquement votre téléphone.',
  tour_theme_bullet_1: 'Chaque mode conserve un contraste élevé et les mêmes codes d’état.',
  tour_theme_bullet_2: 'Vous pourrez rejouer ce guide à tout moment depuis les réglages.',
  tour_background_eyebrow: 'ARRIÈRE-PLAN',
  tour_background_title: 'Protégé même écran éteint',
  tour_background_desc: 'Android maintient le tunnel avec une notification discrète. Elle reprend le même état, la même durée et les mêmes débits que l’accueil.',
  tour_background_bullet_1: 'Les sondes d’interface s’arrêtent en arrière-plan pour économiser la batterie.',
  tour_background_bullet_2: 'La reconnexion automatique garde votre protection lors d’un changement de réseau.',
  replay_tutorial: 'Revoir le tutoriel',
  replay_tutorial_hint: 'Accueil, profils, quota et arrière-plan',
  connection_live: 'Connexion en cours',
  connection_duration: 'Durée',
  connection_speeds: 'Débits',
  vpn_notification_idle: 'Connectez-vous depuis l’accueil pour activer la protection.',
  notification_alerts: 'Annonces, mises à jour et alertes',
  friendly_security: 'Vérification de la sécurité de votre appareil…',
  friendly_security_ok: 'Votre appareil est sécurisé',
  friendly_permission: 'Autorisation VPN Android…',
  friendly_permission_ok: 'Autorisation accordée',
  friendly_permission_denied: 'Autorisation refusée par Android',
  friendly_config: 'Chargement de votre configuration…',
  friendly_config_ok: 'Configuration prête',
  friendly_provisioning: 'Préparation sécurisée du profil…',
  friendly_provisioning_ok: 'Profil sécurisé prêt',
  friendly_syncing: 'Synchronisation avec le service…',
  friendly_synced: 'Données à jour',
  friendly_quota: 'Vérification du forfait…',
  friendly_quota_ok: 'Forfait valide',
  friendly_quota_exhausted: 'Quota épuisé — rechargez votre forfait',
  friendly_expired: 'Abonnement expiré',
  friendly_connecting: 'Connexion au serveur SXB…',
  friendly_handshake: 'Échange de sécurité chiffré…',
  friendly_tunnel: 'Création du tunnel sécurisé…',
  friendly_tunnel_ok: 'Tunnel sécurisé prêt',
  friendly_connected: 'Connexion établie — vous êtes protégé',
  friendly_connected_final: '✅ Connecté — vous naviguez en sécurité',
  friendly_disconnecting: 'Fermeture du tunnel…',
  friendly_disconnected: 'Déconnecté',
  friendly_reconnecting: 'Reconnexion automatique…',
  friendly_revoked: 'Configuration révoquée par l\'administrateur',
  friendly_suspended: 'Compte suspendu — contactez le support',
  friendly_error: 'Une erreur est survenue pendant la connexion',

  // Multi-config
  config_select: 'Sélectionner',
  config_active: 'Active',
  config_inactive: 'Inactive',
  config_max_reached: 'Maximum 2 configurations atteint',
  config_switch: 'Changer de configuration',
  config_saved: 'Configuration sauvegardée',
  config_removed: 'Configuration supprimée',

  // VPN Connections
  vpn_connections: 'CONNEXIONS VPN',
  no_vpn_connections: 'Aucune connexion VPN configurée',
  ask_admin_for_plan: 'Demandez à votre administrateur de créer un forfait',
  connection_expired: 'Expiré',
  connection_revoked: 'Révoqué',
  connection_suspended: 'Suspendu',
  connection_active: 'Actif',
  connection_disabled: 'Désactivé',

  // Quota (unifié — pas de doublon)
  quota_total: 'Total',
  quota_used: 'Utilisé',
  quota_remaining: 'Restant',
  quota_remaining_full: 'Quota restant',
  quota_exhausted: 'Quota épuisé',
  quota_reload: 'Rechargez votre forfait',

  // Expiration
  config_expired: 'Configuration expirée',
  config_expires_at: 'Expire le',

  // Connection Info
  info_protocol: 'Protocole',
  info_last_conn: 'Dernière conn.',
  info_ip_address: 'Adresse IP',
  info_ping: 'Ping',

  // Notifications VPN
  notif_connected: 'VPN connecté',
  notif_disconnected: 'VPN déconnecté',
  notif_reconnecting: 'Reconnexion en cours...',
  notif_error: 'Erreur de connexion VPN',
  notif_kill_switch: 'Kill Switch actif — connexion bloquée',

  // Mise à jour in-app
  update_available_title: 'Nouvelle version disponible',
  update_available_body: 'Une nouvelle version de SXB VPN est prête. Vos données seront conservées.',
  update_current_label: 'Version actuelle',
  update_new_label: 'Nouvelle version',
  update_download: 'Télécharger',
  update_later: 'Plus tard',
  update_downloading: 'Téléchargement…',
  update_downloading_pct: 'Téléchargement… ({pct}%)',
  update_install_prompt: 'Ouverture du programme d\'installation…',
  update_install_error: 'Impossible d\'ouvrir l\'installation. Réessayez.',
  update_download_error: 'Le téléchargement a échoué. Vérifiez votre connexion.',
  update_integrity_error: 'Fichier corrompu ou altéré — installation annulée. Réessayez.',
  update_up_to_date: 'Application à jour',
  update_check_failed: 'Impossible de vérifier les mises à jour',
} as const;
