export const fr = {
  // App
  app_name: 'SXB VPN',
  tagline: 'Naviguez en sécurité',

  // Onboarding
  onboarding_title_1: 'Bienvenue sur SXB VPN',
  onboarding_desc_1: 'Naviguez en toute sécurité grâce à une connexion rapide et protégée, où que vous soyez.',
  onboarding_title_2: 'Connexion simplifiée',
  onboarding_desc_2: 'Activez votre compte avec un simple Token SXB. Pas de configuration, pas de prise de tête.',
  onboarding_title_3: 'Rechargez facilement',
  onboarding_desc_3: 'Ajoutez un forfait en un instant grâce à votre Token Data SXB.',
  onboarding_title_4: 'Prêt à commencer',
  onboarding_desc_4: 'Votre sécurité en ligne commence maintenant. Activez votre compte et naviguez librement.',
  start: 'Commencer',
  next: 'Suivant',
  skip: 'Passer',

  // Auth / Activation
  activate_account_title: 'Activation du compte',
  activate_account_desc: 'Entrez votre Token SXB pour activer votre compte et accéder à la protection VPN.',
  token_user_placeholder: 'SXB-USER-XXXX-XXXX-XXXX',
  paste: 'Coller',
  scan_qr: 'Scanner QR',
  activate: 'Activer',
  activate_btn: 'Activer mon compte',
  activating: 'Activation en cours...',
  activation_success: 'Compte activé avec succès !',
  qr_soon_title: 'QR Code',
  qr_soon_body: "Le scan de QR Code sera disponible dans la prochaine version.\n\nEntrez votre token manuellement ci-dessus.",
  ok: 'OK',
  token_not_found: 'Token introuvable. Vérifiez le code.',
  token_used: 'Token déjà utilisé.',
  token_expired_short: 'Token expiré.',
  network_error: 'Erreur réseau. Réessayez.',

  // Smart Button
  activate_account: 'Activer mon compte',
  activate_plan: 'Activer un forfait',
  connect: 'Se connecter',
  connecting: 'Connexion...',
  disconnect: 'Se déconnecter',
  disconnecting: 'Déconnexion...',
  renew_plan: 'Renouveler mon forfait',
  contact_support: 'Contacter le support',
  loading: 'Chargement...',
  user_default: 'Utilisateur',

  // Home
  greeting_morning: 'Bonjour',
  greeting_afternoon: 'Bonjour',
  greeting_evening: 'Bonsoir',
  greeting_default: 'Bonjour 👋',
  account_active: 'Compte actif',
  account_suspended: 'Compte suspendu',
  protection_active: 'Protection active',
  protection_inactive: 'Protection inactive',
  connecting_status: 'Connexion en cours...',
  tap_to_connect: 'Appuyez pour vous connecter',
  tap_to_disconnect: 'Appuyez pour vous déconnecter',
  view_connection_logs: 'Voir les logs de connexion',
  logs_in_progress: 'Progression…',
  logs_engine_title: 'Logs moteur VPN',
  logs_copy_all: 'Copier',
  logs_copy_a11y: 'Copier tous les logs',
  logs_copy_hint: 'Une touche « Copier » = tout l\'historique (partage ou presse-papiers), prêt à coller.',
  logs_waiting: 'En attente de connexion...',
  card_quota_plan: 'QUOTA DU FORFAIT',
  card_traffic_realtime: 'TRAFIC EN TEMPS RÉEL',
  card_traffic_per_app: 'CONSOMMATION PAR APPLICATION',
  card_connection_info: 'INFORMATIONS DE CONNEXION',
  no_app_data: 'Aucune donnée applicative disponible',
  revocation_msg_revoked: "Cette configuration a été révoquée par l'administrateur.",
  revocation_msg_suspended: 'Votre compte est suspendu. Contactez le support.',
  revocation_msg_expired: 'Votre abonnement a expiré. Renouvelez-le.',
  revocation_msg_disabled: 'Cette configuration est désactivée.',

  // Subscription Card
  current_plan: 'Votre forfait',
  expires_on: 'Expire le',
  no_active_plan: 'Aucun forfait actif',
  add_plan: 'Ajouter un forfait',
  days_left: 'jours restants',
  day_left: 'jour restant',
  expired_plan: 'Forfait expiré',
  of: 'sur',
  gb: 'Go',
  mb: 'Mo',
  kb: 'Ko',

  // Plan Activation
  activate_plan_title: 'Activer un forfait',
  activate_plan_desc: 'Entrez votre Token Data SXB pour ajouter un forfait à votre compte.',
  token_data_placeholder: 'SXB-DATA-XXXX-XXXX-XXXX',
  plan_activating: 'Activation en cours...',
  plan_success: 'Forfait activé avec succès !',
  quota_added: 'Quota ajouté',

  // Navigation
  home: 'Accueil',
  history: 'Historique',
  profile: 'Profil',
  notifications: 'Notifications',
  alerts_tab: 'Alertes',

  // History
  no_history: 'Aucune activité enregistrée',
  account_activated_event: 'Compte activé',
  plan_activated_event: 'Forfait activé',
  vpn_connected_event: 'VPN connecté',
  vpn_disconnected_event: 'VPN déconnecté',
  plan_expired_event: 'Forfait expiré',
  plan_renewed_event: 'Forfait renouvelé',
  filter_all: 'Tout',
  filter_connections: 'Connexions',
  filter_activations: 'Activations',

  // Notifications
  mark_all_read: 'Tout marquer comme lu',
  no_notifications: 'Aucune notification',
  no_notifications_desc: "Vous n'avez pas encore de notifications.",
  notif_plan_expired: 'Votre forfait SXB VPN a expiré.',
  notif_low_quota_100mb: 'Il vous reste 100 Mo de données.',
  notif_expires_tomorrow: 'Votre forfait expire demain.',
  notif_new_config: 'Nouvelle configuration VPN disponible.',
  notif_sync_done: 'Synchronisation terminée.',
  notifications_read_all: 'Tout lire',
  notifications_empty_hint: 'Vous serez averti des événements importants.',
  time_minutes_short: ' min',
  time_hours_short: ' h',
  time_days_short: ' j',

  // Profile
  client_id: 'Identifiant client',
  plan_label: 'Forfait',
  expiration: 'Expiration',
  devices_authorized: 'Appareils autorisés',
  app_version: "Version de l'application",
  logout: 'Déconnexion',
  logout_confirm_title: 'Déconnexion',
  logout_confirm_message: 'Êtes-vous sûr de vouloir vous déconnecter ?',
  logout_confirm_local: 'Votre session locale sera effacée. Votre compte reste actif.',
  logout_confirm_local_short: 'Votre session locale sera effacée.',
  cancel: 'Annuler',
  confirm: 'Confirmer',
  no_expiry: 'Illimité',
  device: 'appareil',
  devices: 'appareils',
  section_personal_info: 'Informations personnelles',
  section_authorized_devices: 'Appareils autorisés',
  section_security_conn: 'Sécurité & Connexion',
  status_no_package: 'Sans forfait',
  status_unknown: 'Inconnu',

  // Settings
  settings: 'Paramètres',
  language_section: 'Langue',
  french: 'Français',
  english: 'English',
  theme_section: 'Apparence',
  theme_dark: 'Sombre',
  theme_light: 'Clair',
  theme_system: 'Système',
  notifications_section: 'Notifications',
  notifications_enable: 'Activer les notifications',
  security_section: 'Sécurité',
  biometrics: 'Déverrouillage biométrique',
  about_section: 'À propos',
  version: 'Version',
  terms: "Conditions d'utilisation",
  privacy_policy: 'Politique de confidentialité',
  cgu_button: 'CGU / Politique de confidentialité',
  cgu_modal_title: 'CGU & Politique de confidentialité',
  close: 'Fermer',
  build_label: 'Build',
  diagnostic_section: 'DIAGNOSTIC',
  diagnostic_subtitle: 'Outils de débogage tunnel VPN (dev only)',
  diagnostic_row: 'Diagnostic VPN',
  dev_badge: 'DEV',
  appearance_lang_section: 'APPARENCE & LANGUE',
  theme_dark_row: 'Thème sombre',
  language_row: 'Langue',
  push_notifications: 'Notifications push',
  plan_expiration_alerts: 'Alertes expiration forfait',
  local_data_section: 'DONNÉES LOCALES',
  stored_data: 'Données stockées',
  clear_local_data_btn: 'Effacer les données locales',
  clear_local_data_title: 'Effacer les données locales',
  clear_local_data_msg: 'Cette action supprime la configuration VPN, les logs et les préférences locales. Votre compte ne sera pas supprimé.',
  clear: 'Effacer',
  data_cleared: 'Données effacées',
  data_cleared_msg: 'Les données locales ont été supprimées.',
  kill_switch_enabled_title: 'Kill Switch activé',
  kill_switch_enabled_msg: 'Toute connexion internet sera bloquée si le VPN se déconnecte.',
  config_synced_title: 'La configuration VPN a été synchronisée depuis le serveur.',
  config_sync_error_msg: 'Impossible de synchroniser la configuration. Vérifiez votre connexion.',
  device_id_row: 'ID Appareil',
  pin_lock_row: 'Verrouillage par code PIN',
  biometrics_row: 'Authentification biométrique',
  biometrics_soon_title: 'Bientôt disponible',
  biometrics_soon_msg: 'La biométrie sera activée dans la prochaine version.',
  package_section: 'FORFAIT',
  quota_used_row: 'Quota utilisé',
  vpn_row_section: 'VPN',
  active_protocol_row: 'Protocole actif',
  auto_value: 'AUTO',
  auto_reconnect_row: 'Reconnexion automatique',
  kill_switch_row: 'Kill Switch',
  on_value: 'ON',
  off_value: 'OFF',
  view_vpn_logs_row: 'Voir les logs VPN',
  security_section_uc: 'SÉCURITÉ',
  about_section_uc: 'À PROPOS',
  notifications_section_uc: 'NOTIFICATIONS',

  // Settings — Compte
  account_section: 'Compte',
  device_id: 'Identifiant appareil',
  subscription_status: 'Statut abonnement',
  subscription_active: 'Actif',
  subscription_expired: 'Expiré',
  subscription_none: 'Aucun forfait',

  // Settings — VPN
  vpn_section: 'VPN',
  refresh_config: 'Actualiser la configuration',
  refreshing_config: 'Synchronisation...',
  refresh_config_success: 'Configuration mise à jour !',
  refresh_config_error: 'Impossible de synchroniser la configuration',
  kill_switch: 'Kill Switch',
  kill_switch_desc: 'Bloquer tout le trafic si le VPN se déconnecte',
  vpn_logs: 'Journaux VPN',
  clear_logs: 'Effacer les journaux',

  // Settings — Données
  data_section: 'Données locales',
  clear_cache: 'Nettoyer le cache local',
  clear_cache_confirm: 'Effacer toutes les données locales ?',
  clear_cache_success: 'Cache effacé avec succès',

  // Support
  support: 'Support',
  faq: 'FAQ',
  faq_q1: 'Comment activer mon compte ?',
  faq_a1: "Entrez votre Token SXB-USER sur l'écran d'activation. Le token vous a été fourni lors de votre inscription.",
  faq_q2: 'Comment ajouter un forfait ?',
  faq_a2: "Appuyez sur « Activer un forfait » et entrez votre Token Data SXB-DATA.",
  faq_q3: 'Que faire si ma connexion ne fonctionne pas ?',
  faq_a3: "Vérifiez votre connexion internet, puis déconnectez et reconnectez le VPN. Si le problème persiste, contactez le support.",
  faq_q4: 'Mon forfait est expiré, que faire ?',
  faq_a4: 'Contactez votre revendeur pour obtenir un nouveau Token Data et activez-le dans l\'application.',
  faq_q5: 'Le VPN reste-t-il actif quand je ferme l\'application ?',
  faq_a5: 'Oui. Un service en premier plan garantit que le tunnel VPN reste actif en arrière-plan et lorsque l\'écran est verrouillé.',
  faq_activate_q: 'Comment activer mon compte ?',
  faq_vpn_ko_q: 'Mon VPN ne se connecte pas',
  faq_vpn_ko_a: 'Vérifiez votre connexion internet, puis assurez-vous que votre forfait est actif et non expiré.',
  faq_renew_q: 'Comment renouveler mon forfait ?',
  faq_devices_q: "Combien d'appareils puis-je utiliser ?",
  faq_devices_a: "Le nombre d'appareils autorisés dépend de votre forfait. Consultez votre profil pour voir la limite.",
  contact_whatsapp: 'WhatsApp',
  contact_email: 'Email',
  contact_discord: 'Discord',
  ticket_subject_placeholder: 'Sujet',
  ticket_message_placeholder: 'Décrivez votre problème...',
  send: 'Envoyer',
  sent: 'Envoyé !',
  create_ticket: 'Créer un ticket',
  my_tickets: 'Mes tickets',
  contact_us: 'Nous contacter',
  // duplicate removed
  ticket_submit: 'Envoyer',
  ticket_submitting: 'Envoi en cours...',
  ticket_success: 'Votre message a été envoyé avec succès.',
  ticket_load_failed: 'Impossible de charger vos tickets. Vérifiez votre connexion.',
  ticket_send_failed: 'Le ticket n’a pas été envoyé. Vérifiez votre connexion et réessayez.',
  ticket_empty: 'Vous n’avez encore aucun ticket.',
  ticket_open: 'Ouvert',
  ticket_in_progress: 'En cours',
  ticket_resolved: 'Résolu',
  ticket_closed: 'Clôturé',
  ticket_updated_at: 'Mis à jour',
  hero_sub: 'Notre équipe est disponible pour vous aider.',

  // Errors
  error_invalid_token: 'Token invalide. Vérifiez et réessayez.',
  error_expired_token: 'Ce token a expiré.',
  error_suspended: 'Votre compte est suspendu. Contactez le support.',
  error_no_network: 'Connexion impossible. Vérifiez votre réseau.',
  error_server: 'Erreur serveur. Veuillez réessayer plus tard.',
  error_generic: "Une erreur s'est produite. Veuillez réessayer.",
  error_quota_empty: 'Quota insuffisant.',
  error_vpn_permission: "Permission VPN requise. Accordez l'accès dans les paramètres Android.",
  retry: 'Réessayer',
  back: 'Retour',
  oops: 'Oups !',

  // Time
  just_now: "À l'instant",
  minutes_ago: 'min',
  hours_ago: 'h',
  today: "Aujourd'hui",
  yesterday: 'Hier',

  // Status
  active: 'Actif',
  inactive: 'Inactif',
  expired: 'Expiré',
  suspended_status: 'Suspendu',
  no_package_status: 'Aucun forfait',

  // Onboarding — Sécurité totale / One-click / etc.
  onboarding_security_title: 'Sécurité totale',
  onboarding_security_desc: 'Votre connexion chiffrée, votre identité protégée. Partout. Toujours.',
  onboarding_oneclick_title: 'Un clic suffit',

  // VPN — Paramètres
  auto_reconnect: 'Reconnexion automatique',
  auto_reconnect_desc: 'Se reconnecter automatiquement si la connexion est perdue',

  // VPN — Trafic
  traffic_realtime: 'TRAFIC EN TEMPS RÉEL',
  traffic_sent: 'Envoyé',
  traffic_received: 'Reçu',
  traffic_speed: 'Débit',
  traffic_upload: 'Upload',
  traffic_download: 'Download',
  traffic_session: 'Session',

  // StepLogs — Étapes techniques (labels bruts, gardés pour compat)
  step_preparing: 'Préparation…',
  step_checking_security: 'Vérification de sécurité…',
  step_security_ok: 'Environnement sécurisé',
  step_loading_config: 'Chargement de la configuration…',
  step_config_loaded: 'Configuration chargée',
  step_provisioning: 'Provisionnement sécurisé…',
  step_provisioned: 'Configuration provisionnée',
  step_syncing: 'Synchronisation…',
  step_synced: 'Données synchronisées',
  step_connecting: 'Connexion au serveur…',
  step_handshake: 'Négociation sécurisée…',
  step_establishing_tunnel: 'Établissement du tunnel…',
  step_tunnel_ready: 'Tunnel sécurisé prêt',
  step_vpn_active: 'VPN connecté',
  step_error: 'Erreur de connexion',
  step_disconnecting: 'Déconnexion…',
  step_disconnected: 'VPN déconnecté',
  step_reconnecting: 'Reconnexion automatique…',
  step_quota_check: 'Vérification du quota…',
  step_quota_ok: 'Quota suffisant',
  step_quota_exhausted: 'Quota épuisé',
  step_expired: 'Abonnement expiré',
  step_revoked: 'Configuration révoquée',
  step_suspended: 'Compte suspendu',
  step_permission_check: 'Vérification des permissions…',
  step_permission_granted: 'Permission accordée',
  step_permission_denied: 'Permission refusée',

  // StepLogs — Formulations grand public (affichées à l'utilisateur)
  friendly_header: 'Connexion en cours',
  friendly_a11y_progress: 'Progression de la connexion VPN',
  friendly_preparing: 'Préparation de la connexion…',
  walkthrough_welcome_title: 'Guide de démarrage',
  walkthrough_welcome_desc: 'Bienvenue ! Laissez-nous vous montrer comment utiliser votre nouvelle application SXB VPN.',
  walkthrough_vpn_btn_title: 'Bouton de Connexion',
  walkthrough_vpn_btn_desc: 'Appuyez ici pour activer ou désactiver instantanément votre protection VPN.',
  walkthrough_config_title: 'Vos Connexions',
  walkthrough_config_desc: 'Basculez facilement entre vos différentes configurations VPN ici.',
  walkthrough_quota_title: 'Suivi Data',
  walkthrough_quota_desc: 'Surveillez votre consommation en temps réel et votre quota restant.',
  walkthrough_actions_title: 'Actions Rapides',
  walkthrough_actions_desc: 'Accédez à votre historique, au support ou activez un nouveau forfait.',
  walkthrough_finish: "C'est parti !",
  friendly_security: 'Vérification de la sécurité de votre appareil…',
  friendly_security_ok: 'Votre appareil est sécurisé',
  friendly_permission: 'Autorisation VPN Android…',
  friendly_permission_ok: 'Autorisation accordée',
  friendly_permission_denied: 'Autorisation refusée par Android',
  friendly_config: 'Chargement de votre configuration…',
  friendly_config_ok: 'Configuration prête',
  friendly_provisioning: 'Préparation sécurisée du profil…',
  friendly_provisioning_ok: 'Profil sécurisé prêt',
  friendly_syncing: 'Synchronisation avec le service…',
  friendly_synced: 'Données à jour',
  friendly_quota: 'Vérification du forfait…',
  friendly_quota_ok: 'Forfait valide',
  friendly_quota_exhausted: 'Quota épuisé — rechargez votre forfait',
  friendly_expired: 'Abonnement expiré',
  friendly_connecting: 'Connexion au serveur SXB…',
  friendly_handshake: 'Échange de sécurité chiffré…',
  friendly_tunnel: 'Création du tunnel sécurisé…',
  friendly_tunnel_ok: 'Tunnel sécurisé prêt',
  friendly_connected: 'Connexion établie — vous êtes protégé',
  friendly_connected_final: '✅ Connecté — vous naviguez en sécurité',
  friendly_disconnecting: 'Fermeture du tunnel…',
  friendly_disconnected: 'Déconnecté',
  friendly_reconnecting: 'Reconnexion automatique…',
  friendly_revoked: 'Configuration révoquée par l\'administrateur',
  friendly_suspended: 'Compte suspendu — contactez le support',
  friendly_error: 'Une erreur est survenue pendant la connexion',

  // Multi-config
  config_select: 'Sélectionner',
  config_active: 'Active',
  config_inactive: 'Inactive',
  config_max_reached: 'Maximum 2 configurations atteint',
  config_switch: 'Changer de configuration',
  config_saved: 'Configuration sauvegardée',
  config_removed: 'Configuration supprimée',

  // VPN Connections
  vpn_connections: 'CONNEXIONS VPN',
  no_vpn_connections: 'Aucune connexion VPN configurée',
  ask_admin_for_plan: 'Demandez à votre administrateur de créer un forfait',
  connection_expired: 'Expiré',
  connection_revoked: 'Révoqué',
  connection_suspended: 'Suspendu',
  connection_active: 'Actif',
  connection_disabled: 'Désactivé',

  // Quota (unifié — pas de doublon)
  quota_total: 'Total',
  quota_used: 'Utilisé',
  quota_remaining: 'Restant',
  quota_remaining_full: 'Quota restant',
  quota_exhausted: 'Quota épuisé',
  quota_reload: 'Rechargez votre forfait',

  // Expiration
  config_expired: 'Configuration expirée',
  config_expires_at: 'Expire le',

  // Connection Info
  info_protocol: 'Protocole',
  info_last_conn: 'Dernière conn.',
  info_ip_address: 'Adresse IP',
  info_ping: 'Ping',

  // Notifications VPN
  notif_connected: 'VPN connecté',
  notif_disconnected: 'VPN déconnecté',
  notif_reconnecting: 'Reconnexion en cours...',
  notif_error: 'Erreur de connexion VPN',
  notif_kill_switch: 'Kill Switch actif — connexion bloquée',

  // Mise à jour in-app
  update_available_title: 'Nouvelle version disponible',
  update_available_body: 'Une nouvelle version de SXB VPN est prête. Vos données seront conservées.',
  update_current_label: 'Version actuelle',
  update_new_label: 'Nouvelle version',
  update_download: 'Télécharger',
  update_later: 'Plus tard',
  update_downloading: 'Téléchargement…',
  update_downloading_pct: 'Téléchargement… ({pct}%)',
  update_install_prompt: 'Ouverture du programme d\'installation…',
  update_install_error: 'Impossible d\'ouvrir l\'installation. Réessayez.',
  update_download_error: 'Le téléchargement a échoué. Vérifiez votre connexion.',
  update_up_to_date: 'Application à jour',
  update_check_failed: 'Impossible de vérifier les mises à jour',
} as const;
